// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "csharptorust_lib";





        [DllImport(__DllName, EntryPoint = "add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int add(int a, int b);

        [DllImport(__DllName, EntryPoint = "multiply", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int multiply(int a, int b);

        [DllImport(__DllName, EntryPoint = "get_message", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* get_message();

        [DllImport(__DllName, EntryPoint = "free_message", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_message(byte* ptr);


    }



}
