// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "callback_demo";





        [DllImport(__DllName, EntryPoint = "register_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void register_callback(delegate* unmanaged[Cdecl]<int, int> callback);

        [DllImport(__DllName, EntryPoint = "trigger_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int trigger_callback(int value);

        [DllImport(__DllName, EntryPoint = "clear_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void clear_callback();


    }



}
