// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;

namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "hezhou_scripting";

        [DllImport(__DllName, EntryPoint = "scripting_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void* scripting_init();

        [DllImport(__DllName, EntryPoint = "scripting_shutdown", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void scripting_shutdown(void* manager);

        [DllImport(__DllName, EntryPoint = "scripting_load", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int scripting_load(void* manager, byte* dll_path);

        [DllImport(__DllName, EntryPoint = "scripting_register_sync_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void scripting_register_sync_callback(void* manager, byte* name, delegate* unmanaged[Cdecl]<ScriptValue, nuint, ScriptValue> callback, byte* description, byte* signature, nuint context);

        [DllImport(__DllName, EntryPoint = "scripting_register_async_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void scripting_register_async_callback(void* manager, byte* name, delegate* unmanaged[Cdecl]<ScriptValue, nuint, nuint, void> callback, byte* description, nuint context);

        [DllImport(__DllName, EntryPoint = "scripting_register_task_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void scripting_register_task_callback(void* manager, byte* name, delegate* unmanaged[Cdecl]<ScriptValue, nuint, nuint, nuint, void> callback, byte* description, [MarshalAs(UnmanagedType.U1)] bool supports_progress, nuint context);

        [DllImport(__DllName, EntryPoint = "scripting_trigger_sync", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ScriptValue scripting_trigger_sync(void* manager, byte* name, ScriptValue arg);

        [DllImport(__DllName, EntryPoint = "scripting_notify_completion", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void scripting_notify_completion(void* manager, ScriptValue result);

        [DllImport(__DllName, EntryPoint = "scripting_notify_progress", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void scripting_notify_progress(void* manager, float progress);

        [DllImport(__DllName, EntryPoint = "scripting_unregister_callback", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void scripting_unregister_callback(void* manager, byte* name);
    }
}